In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 

pd.set_option('display.max_columns', None)

In [2]:
population_path = '/Users/muhammadhamza/striker_era_ranking/data/raw/external/unpopulation_dataportal_20260827013637.csv'
balondor_path = '/Users/muhammadhamza/striker_era_ranking/data/raw/ballon_dor/ballon_dor_winners.csv'
player_path = '/Users/muhammadhamza/striker_era_ranking/data/raw/fbref/all_seasons_combined.csv'
df_pop = pd.read_csv(population_path)
df_bdr = pd.read_csv(balondor_path)
df_player = pd.read_csv(player_path)

In [3]:
df_pop.head()

,IndicatorId,IndicatorName,IndicatorShortName,Source,SourceYear,Author,LocationId,Location,Iso2,Iso3,TimeId,Time,VariantId,Variant,SexId,Sex,AgeId,AgeStart,AgeEnd,Age,CategoryId,Category,EstimateTypeId,EstimateType,EstimateMethodId,EstimateMethod,Value
0,47,Population by 1-year age groups and sex,Annual population by 1-year age groups and by sex,World Population Prospects,2024,United Nations Population Division,4,Afghanistan,AF,AFG,43,1992,4,Median,1,Male,113,16,16,16,0,Not applicable,1,Model-based Estimates,3,Projection,150255.0
1,47,Population by 1-year age groups and sex,Annual population by 1-year age groups and by sex,World Population Prospects,2024,United Nations Population Division,4,Afghanistan,AF,AFG,43,1992,4,Median,1,Male,114,17,17,17,0,Not applicable,1,Model-based Estimates,3,Projection,145029.5
2,47,Population by 1-year age groups and sex,Annual population by 1-year age groups and by sex,World Population Prospects,2024,United Nations Population Division,4,Afghanistan,AF,AFG,43,1992,4,Median,1,Male,115,18,18,18,0,Not applicable,1,Model-based Estimates,3,Projection,139522.0
3,47,Population by 1-year age groups and sex,Annual population by 1-year age groups and by sex,World Population Prospects,2024,United Nations Population Division,4,Afghanistan,AF,AFG,43,1992,4,Median,1,Male,116,19,19,19,0,Not applicable,1,Model-based Estimates,3,Projection,133543.0
4,47,Population by 1-year age groups and sex,Annual population by 1-year age groups and by sex,World Population Prospects,2024,United Nations Population Division,4,Afghanistan,AF,AFG,43,1992,4,Median,1,Male,92,20,20,20,0,Not applicable,1,Model-based Estimates,3,Projection,127710.5

In [4]:
df_pop['Variant'].unique()

array(['Median'], dtype=object)

In [5]:
population_raw = df_pop[['Time', 'Location', 'Age', 'Value']].copy()

population_raw = population_raw.rename(columns={
    'Time': 'Year', 
    'Location': 'Country',
    'Value': 'Population'
})

population_raw.head()

   Year      Country  Age  Population
0  1992  Afghanistan   16    150255.0
1  1992  Afghanistan   17    145029.5
2  1992  Afghanistan   18    139522.0
3  1992  Afghanistan   19    133543.0
4  1992  Afghanistan   20    127710.5

In [6]:
duplicate_check = population_raw.duplicated(subset=[
    'Year', 'Country', 'Age'
]).sum()

duplicate_check

0

In [7]:
population_raw['Country'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra',
       'Angola', 'Antigua and Barbuda', 'Azerbaijan', 'Argentina',
       'Australia', 'Austria', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Armenia', 'Barbados', 'Belgium', 'Bermuda', 'Bhutan',
       'Bolivia (Plurinational State of)', 'Bosnia and Herzegovina',
       'Botswana', 'Brazil', 'Belize', 'Solomon Islands',
       'British Virgin Islands', 'Brunei Darussalam', 'Bulgaria',
       'Myanmar', 'Burundi', 'Belarus', 'Cambodia', 'Cameroon', 'Canada',
       'Cabo Verde', 'Cayman Islands', 'Central African Republic',
       'Sri Lanka', 'Chad', 'Chile', 'China',
       'China, Taiwan Province of China', 'Colombia', 'Comoros',
       'Mayotte', 'Congo', 'Democratic Republic of the Congo',
       'Cook Islands', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus',
       'Czechia', 'Benin', 'Denmark', 'Dominica', 'Dominican Republic',
       'Ecuador', 'El Salvador', 'Equatorial Guinea', 'Ethiopia',
       'Eritrea', 'Estonia', 'Faroe Islands',
       'Falkland Islands (Malvinas)', 'Fiji', 'Finland', 'France',
       'French Guiana', 'French Polynesia', 'Djibouti', 'Gabon',
       'Georgia', 'Gambia', 'State of Palestine', 'Germany', 'Ghana',
       'Gibraltar', 'Kiribati', 'Greece', 'Greenland', 'Grenada',
       'Guadeloupe', 'Guam', 'Guatemala', 'Guinea', 'Guyana', 'Haiti',
       'Honduras', 'China, Hong Kong SAR', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran (Islamic Republic of)', 'Iraq', 'Ireland',
       'Israel', 'Italy', "Côte d'Ivoire", 'Jamaica', 'Japan',
       'Kazakhstan', 'Jordan', 'Kenya', "Dem. People's Rep. of Korea",
       'Republic of Korea', 'Kosovo (under UNSC res. 1244)', 'Kuwait',
       'Kyrgyzstan', "Lao People's Democratic Republic", 'Lebanon',
       'Lesotho', 'Latvia', 'Liberia', 'Libya', 'Liechtenstein',
       'Lithuania', 'Luxembourg', 'China, Macao SAR', 'Madagascar',
       'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Martinique',
       'Mauritania', 'Mauritius', 'Mexico', 'Monaco', 'Mongolia',
       'Republic of Moldova', 'Montenegro', 'Montserrat', 'Morocco',
       'Mozambique', 'Oman', 'Namibia', 'Republic of Naoero', 'Nepal',
       'Netherlands', 'Curaçao', 'Aruba', 'Sint Maarten (Dutch part)',
       'Bonaire, Sint Eustatius and Saba', 'New Caledonia', 'Vanuatu',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'Norway',
       'Northern Mariana Islands', 'Micronesia (Fed. States of)',
       'Marshall Islands', 'Palau', 'Pakistan', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Guinea-Bissau', 'Timor-Leste', 'Puerto Rico', 'Qatar',
       'Réunion', 'Romania', 'Russian Federation', 'Rwanda',
       'Saint Barthélemy', 'Saint Helena', 'Saint Kitts and Nevis',
       'Anguilla', 'Saint Lucia', 'Saint Martin (French part)',
       'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines',
       'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal',
       'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia',
       'Viet Nam', 'Slovenia', 'Somalia', 'South Africa', 'Zimbabwe',
       'Spain', 'South Sudan', 'Sudan', 'Western Sahara', 'Suriname',
       'Eswatini', 'Sweden', 'Switzerland', 'Syrian Arab Republic',
       'Tajikistan', 'Thailand', 'Togo', 'Tokelau', 'Tonga',
       'Trinidad and Tobago', 'United Arab Emirates', 'Tunisia',
       'Türkiye', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu',
       'Uganda', 'Ukraine', 'North Macedonia', 'Egypt', 'United Kingdom',
       'Guernsey', 'Jersey', 'Isle of Man', 'United Republic of Tanzania',
       'United States of America', 'United States Virgin Islands',
       'Burkina Faso', 'Uruguay', 'Uzbekistan',
       'Venezuela (Bolivarian Republic of)', 'Wallis and Futuna Islands',
       'Samoa', 'Yemen', 'Zambia'], dtype=object)

In [8]:
country_to_continent = {

    # =========================
    # AFRICA
    # =========================
    'Algeria': 'Africa',
    'Angola': 'Africa',
    'Benin': 'Africa',
    'Botswana': 'Africa',
    'Burkina Faso': 'Africa',
    'Burundi': 'Africa',
    'Cabo Verde': 'Africa',
    'Cameroon': 'Africa',
    'Central African Republic': 'Africa',
    'Chad': 'Africa',
    'Comoros': 'Africa',
    'Congo': 'Africa',
    'Democratic Republic of the Congo': 'Africa',
    "Côte d'Ivoire": 'Africa',
    'Djibouti': 'Africa',
    'Egypt': 'Africa',
    'Equatorial Guinea': 'Africa',
    'Eritrea': 'Africa',
    'Eswatini': 'Africa',
    'Ethiopia': 'Africa',
    'Gabon': 'Africa',
    'Gambia': 'Africa',
    'Ghana': 'Africa',
    'Guinea': 'Africa',
    'Guinea-Bissau': 'Africa',
    'Kenya': 'Africa',
    'Lesotho': 'Africa',
    'Liberia': 'Africa',
    'Libya': 'Africa',
    'Madagascar': 'Africa',
    'Malawi': 'Africa',
    'Mali': 'Africa',
    'Mauritania': 'Africa',
    'Mauritius': 'Africa',
    'Mayotte': 'Africa',
    'Morocco': 'Africa',
    'Mozambique': 'Africa',
    'Namibia': 'Africa',
    'Niger': 'Africa',
    'Nigeria': 'Africa',
    'Réunion': 'Africa',
    'Rwanda': 'Africa',
    'Saint Helena': 'Africa',
    'Sao Tome and Principe': 'Africa',
    'Senegal': 'Africa',
    'Seychelles': 'Africa',
    'Sierra Leone': 'Africa',
    'Somalia': 'Africa',
    'South Africa': 'Africa',
    'South Sudan': 'Africa',
    'Sudan': 'Africa',
    'Togo': 'Africa',
    'Tunisia': 'Africa',
    'Uganda': 'Africa',
    'United Republic of Tanzania': 'Africa',
    'Western Sahara': 'Africa',
    'Zambia': 'Africa',
    'Zimbabwe': 'Africa',

    # =========================
    # EUROPE
    # =========================
    'Albania': 'Europe',
    'Andorra': 'Europe',
    'Armenia': 'Europe',
    'Austria': 'Europe',
    'Belarus': 'Europe',
    'Belgium': 'Europe',
    'Bosnia and Herzegovina': 'Europe',
    'Bulgaria': 'Europe',
    'Croatia': 'Europe',
    'Czechia': 'Europe',
    'Denmark': 'Europe',
    'Estonia': 'Europe',
    'Faroe Islands': 'Europe',
    'Finland': 'Europe',
    'France': 'Europe',
    'Georgia': 'Europe',
    'Germany': 'Europe',
    'Gibraltar': 'Europe',
    'Greece': 'Europe',
    'Guernsey': 'Europe',
    'Hungary': 'Europe',
    'Iceland': 'Europe',
    'Ireland': 'Europe',
    'Isle of Man': 'Europe',
    'Italy': 'Europe',
    'Jersey': 'Europe',
    'Kosovo (under UNSC res. 1244)': 'Europe',
    'Latvia': 'Europe',
    'Liechtenstein': 'Europe',
    'Lithuania': 'Europe',
    'Luxembourg': 'Europe',
    'Malta': 'Europe',
    'Monaco': 'Europe',
    'Montenegro': 'Europe',
    'Netherlands': 'Europe',
    'North Macedonia': 'Europe',
    'Norway': 'Europe',
    'Poland': 'Europe',
    'Portugal': 'Europe',
    'Republic of Moldova': 'Europe',
    'Romania': 'Europe',
    'Russian Federation': 'Europe',
    'San Marino': 'Europe',
    'Serbia': 'Europe',
    'Slovakia': 'Europe',
    'Slovenia': 'Europe',
    'Spain': 'Europe',
    'Sweden': 'Europe',
    'Switzerland': 'Europe',
    'Türkiye': 'Europe',
    'Ukraine': 'Europe',
    'United Kingdom': 'Europe',

    # =========================
    # NORTH AMERICA
    # =========================
    'American Samoa': 'Oceania',  # geographically Oceania
    'Antigua and Barbuda': 'North America',
    'Bahamas': 'North America',
    'Barbados': 'North America',
    'Belize': 'North America',
    'Bermuda': 'North America',
    'British Virgin Islands': 'North America',
    'Canada': 'North America',
    'Cayman Islands': 'North America',
    'Costa Rica': 'North America',
    'Cuba': 'North America',
    'Curaçao': 'North America',
    'Dominica': 'North America',
    'Dominican Republic': 'North America',
    'El Salvador': 'North America',
    'Greenland': 'North America',
    'Grenada': 'North America',
    'Guadeloupe': 'North America',
    'Guatemala': 'North America',
    'Haiti': 'North America',
    'Honduras': 'North America',
    'Jamaica': 'North America',
    'Martinique': 'North America',
    'Mexico': 'North America',
    'Montserrat': 'North America',
    'Nicaragua': 'North America',
    'Panama': 'North America',
    'Puerto Rico': 'North America',
    'Saint Barthélemy': 'North America',
    'Saint Kitts and Nevis': 'North America',
    'Saint Lucia': 'North America',
    'Saint Martin (French part)': 'North America',
    'Saint Pierre and Miquelon': 'North America',
    'Saint Vincent and the Grenadines': 'North America',
    'Sint Maarten (Dutch part)': 'North America',
    'Trinidad and Tobago': 'North America',
    'Turks and Caicos Islands': 'North America',
    'United States of America': 'North America',
    'United States Virgin Islands': 'North America',
    'Anguilla': 'North America',
    'Aruba': 'North America',
    'Bonaire, Sint Eustatius and Saba': 'North America',
    'Guam': 'Oceania',
    'Northern Mariana Islands': 'Oceania',

    # =========================
    # SOUTH AMERICA
    # =========================
    'Argentina': 'South America',
    'Bolivia (Plurinational State of)': 'South America',
    'Brazil': 'South America',
    'Chile': 'South America',
    'Colombia': 'South America',
    'Ecuador': 'South America',
    'Falkland Islands (Malvinas)': 'South America',
    'French Guiana': 'South America',
    'Guyana': 'South America',
    'Paraguay': 'South America',
    'Peru': 'South America',
    'Suriname': 'South America',
    'Uruguay': 'South America',
    'Venezuela (Bolivarian Republic of)': 'South America',

    # =========================
    # ASIA
    # =========================
    'Afghanistan': 'Asia',
    'Azerbaijan': 'Asia',
    'Bahrain': 'Asia',
    'Bangladesh': 'Asia',
    'Bhutan': 'Asia',
    'Brunei Darussalam': 'Asia',
    'Cambodia': 'Asia',
    'China': 'Asia',
    'China, Hong Kong SAR': 'Asia',
    'China, Macao SAR': 'Asia',
    'China, Taiwan Province of China': 'Asia',
    'Cyprus': 'Asia',
    'India': 'Asia',
    'Indonesia': 'Asia',
    'Iran (Islamic Republic of)': 'Asia',
    'Iraq': 'Asia',
    'Israel': 'Asia',
    'Japan': 'Asia',
    'Jordan': 'Asia',
    'Kazakhstan': 'Asia',
    'Kuwait': 'Asia',
    'Kyrgyzstan': 'Asia',
    "Lao People's Democratic Republic": 'Asia',
    'Lebanon': 'Asia',
    'Malaysia': 'Asia',
    'Maldives': 'Asia',
    'Mongolia': 'Asia',
    'Myanmar': 'Asia',
    'Nepal': 'Asia',
    'Dem. People\'s Rep. of Korea': 'Asia',
    'Republic of Korea': 'Asia',
    'Oman': 'Asia',
    'Pakistan': 'Asia',
    'Philippines': 'Asia',
    'Qatar': 'Asia',
    'Saudi Arabia': 'Asia',
    'Singapore': 'Asia',
    'Sri Lanka': 'Asia',
    'State of Palestine': 'Asia',
    'Syrian Arab Republic': 'Asia',
    'Tajikistan': 'Asia',
    'Thailand': 'Asia',
    'Timor-Leste': 'Asia',
    'Turkmenistan': 'Asia',
    'United Arab Emirates': 'Asia',
    'Uzbekistan': 'Asia',
    'Viet Nam': 'Asia',
    'Yemen': 'Asia',

    # =========================
    # OCEANIA
    # =========================
    'American Samoa': 'Oceania',
    'Australia': 'Oceania',
    'Cook Islands': 'Oceania',
    'Fiji': 'Oceania',
    'French Polynesia': 'Oceania',
    'Guam': 'Oceania',
    'Kiribati': 'Oceania',
    'Marshall Islands': 'Oceania',
    'Micronesia (Fed. States of)': 'Oceania',
    'Nauru': 'Oceania',
    'Republic of Naoero': 'Oceania',
    'New Caledonia': 'Oceania',
    'New Zealand': 'Oceania',
    'Niue': 'Oceania',
    'Northern Mariana Islands': 'Oceania',
    'Palau': 'Oceania',
    'Papua New Guinea': 'Oceania',
    'Samoa': 'Oceania',
    'Solomon Islands': 'Oceania',
    'Tokelau': 'Oceania',
    'Tonga': 'Oceania',
    'Tuvalu': 'Oceania',
    'Vanuatu': 'Oceania',
    'Wallis and Futuna Islands': 'Oceania',
}


population_raw['Continent'] = population_raw['Country'].map(country_to_continent)

population_raw.head()

   Year      Country  Age  Population Continent
0  1992  Afghanistan   16    150255.0      Asia
1  1992  Afghanistan   17    145029.5      Asia
2  1992  Afghanistan   18    139522.0      Asia
3  1992  Afghanistan   19    133543.0      Asia
4  1992  Afghanistan   20    127710.5      Asia

In [9]:
population_continent = (
    population_raw.groupby(['Year', 'Continent', 'Age'], as_index=False)['Population'].sum()
)

population_continent.head()

   Year Continent  Age  Population
0  1992    Africa   16   7437675.5
1  1992    Africa   17   7183377.0
2  1992    Africa   18   6929948.0
3  1992    Africa   19   6699214.0
4  1992    Africa   20   6477465.5

In [10]:
duplicate_check_cont = population_continent.duplicated(subset=[
    'Year', 'Continent', 'Age'
]).sum()

duplicate_check_cont

0

In [11]:
eligible_pop = (
    population_continent.groupby(['Year', 'Continent'], as_index=False)['Population'].sum()
)

eligible_pop.head()

   Year      Continent   Population
0  1992         Africa  108196286.5
1  1992           Asia  584063410.5
2  1992         Europe  122068061.5
3  1992  North America   72416999.5
4  1992        Oceania    4599999.0

In [26]:
df_player.head()

,player,nationality,position,team,league,age,matches,minutes,goals,assists,season,assists_missing,ga_per_90
0,Agustín Abadía,ESP,MF,Compostela,La Liga,33.0,14,378,0,0,1995-1996,True,0.0
1,Beniamino Abate,ITA,GK,Cagliari,Serie A,33.0,15,1350,0,0,1995-1996,True,0.0
2,Giovanni Abate,ITA,MF,Sampdoria,Serie A,19.0,1,56,0,0,1995-1996,True,0.0
3,Denis Abed,FRA,FW,Lille,Division 1,26.0,14,925,0,0,1995-1996,True,0.0
4,Gary Ablett,ENG,DF,Everton,Premier League,29.0,13,1017,0,0,1995-1996,False,0.0

In [28]:
df_player['nationality'].unique()

array(['ESP', 'ITA', 'FRA', 'ENG', 'NGA', 'BEN', 'NOR', 'TUR', 'BEL',
       'GER', 'BRA', 'NAN', 'AUS', 'DEN', 'SWE', 'CRO', 'PAR', 'SRB',
       'ARG', 'MAD', 'COL', 'ARM', 'HAI', 'IRL', 'GUI', 'POL', 'CIV',
       'BUL', 'MNE', 'ALG', 'CZE', 'NED', 'ISL', 'RUS', 'CMR', 'NIR',
       'WAL', 'TUN', 'GDR', 'SCO', 'USA', 'AUT', 'MAR', 'SUI', 'GRE',
       'SLE', 'MTQ', 'URU', 'POR', 'MLI', 'ROU', 'GUF', 'LBR', 'PER',
       'PAN', 'UKR', 'SVK', 'GLP', 'JAM', 'COD', 'SEN', 'SVN', 'RSA',
       'MSR', 'AZE', 'BIH', 'BRB', 'ZIM', 'HON', 'TRI', 'LTU', 'GEO',
       'CIS', 'GHA', 'VEN', 'EQG', 'BOL', 'MKD', 'HUN', 'YUG', 'CHA',
       'FIN', 'CHI', 'EGY', 'CYP', 'ISR', 'ALB', 'URS', 'LUX', 'TOG',
       'CGO', 'BLR', 'REU', 'GUY', 'CAN', 'ANG', 'CRC', 'CPV', 'EST',
       'IRN', 'SKN', 'MCO', 'GIB', 'KOR', 'NIG', 'BER', 'MWI', 'MDA',
       'GNB', 'CHN', 'MAS', 'SCG', 'ECU', 'JPN', 'LVA', 'TAH', 'MEX',
       'ZAM', 'NAM', 'SMN', 'DOM', 'MTN', 'NZL', 'BFA', 'LIB', 'SEY',
       'COM', 'LIE', 'MLT', 'GAB', 'SMR', 'GRN', 'NCL', 'QAT', 'MRI',
       'PHI', 'LBY', 'PAK', 'ATG', 'ERI', 'MOZ', 'CTA', 'LAO', 'KEN',
       'CAM', 'KVX', 'TJK', 'OMA', 'KAZ', 'BDI', 'SOM', 'SUR', 'CUW',
       'IDN', 'FRO', 'GAM', 'PRK', 'IRQ', 'UGA', 'THA', 'SLV', 'BAN',
       'GUA', 'CUB', 'TAN', 'UZB', 'PLE'], dtype=object)

In [13]:
nationality_to_continent = {
    
    # Europe
    'ESP': 'Europe',
    'ITA': 'Europe',
    'FRA': 'Europe',
    'ENG': 'Europe',
    'NOR': 'Europe',
    'TUR': 'Europe',
    'BEL': 'Europe',
    'DEN': 'Europe',
    'SWE': 'Europe',
    'CRO': 'Europe',
    'SRB': 'Europe',
    'ARM': 'Europe',
    'IRL': 'Europe',
    'POL': 'Europe',
    'BUL': 'Europe',
    'MNE': 'Europe',
    'CZE': 'Europe',
    'NED': 'Europe',
    'ISL': 'Europe',
    'RUS': 'Europe',
    'NIR': 'Europe',
    'WAL': 'Europe',
    'GDR': 'Europe',
    'SCO': 'Europe',
    'AUT': 'Europe',
    'SUI': 'Europe',
    'GRE': 'Europe',
    'POR': 'Europe',
    'ROU': 'Europe',
    'UKR': 'Europe',
    'SVK': 'Europe',
    'SVN': 'Europe',
    'BIH': 'Europe',
    'LTU': 'Europe',
    'GEO': 'Europe',
    'CIS': 'Europe',
    'MKD': 'Europe',
    'HUN': 'Europe',
    'YUG': 'Europe',
    'FIN': 'Europe',
    'ALB': 'Europe',
    'URS': 'Europe',
    'LUX': 'Europe',
    'BLR': 'Europe',
    'MDA': 'Europe',
    'LVA': 'Europe',
    'SCG': 'Europe',
    'LIE': 'Europe',
    'MLT': 'Europe',
    'SMR': 'Europe',
    'MCO': 'Europe',
    'GIB': 'Europe',
    'FRO': 'Europe',
    'KVX': 'Europe',
    
    # Africa
    'NGA': 'Africa',
    'BEN': 'Africa',
    'CIV': 'Africa',
    'GUI': 'Africa',
    'ALG': 'Africa',
    'CMR': 'Africa',
    'TUN': 'Africa',
    'MAR': 'Africa',
    'SLE': 'Africa',
    'MLI': 'Africa',
    'LBR': 'Africa',
    'COD': 'Africa',
    'SEN': 'Africa',
    'RSA': 'Africa',
    'ZIM': 'Africa',
    'GHA': 'Africa',
    'CHA': 'Africa',
    'EGY': 'Africa',
    'TOG': 'Africa',
    'CGO': 'Africa',
    'REU': 'Africa',
    'ANG': 'Africa',
    'CPV': 'Africa',
    'MWI': 'Africa',
    'GNB': 'Africa',
    'ZAM': 'Africa',
    'NAM': 'Africa',
    'BFA': 'Africa',
    'LIB': 'Africa',
    'SEY': 'Africa',
    'COM': 'Africa',
    'GAB': 'Africa',
    'LBY': 'Africa',
    'ERI': 'Africa',
    'MOZ': 'Africa',
    'KEN': 'Africa',
    'BDI': 'Africa',
    'SOM': 'Africa',
    'GAM': 'Africa',
    'UGA': 'Africa',
    'MAD': 'Africa',
    'TAN': 'Africa',
    'NIG': 'Africa',
    'EQG': 'Africa',
    
    # South America
    'BRA': 'South America',
    'PAR': 'South America',
    'ARG': 'South America',
    'COL': 'South America',
    'URU': 'South America',
    'PER': 'South America',
    'VEN': 'South America',
    'BOL': 'South America',
    'CHI': 'South America',
    'ECU': 'South America',
    'GUY': 'South America',
    'SUR': 'South America',
    'GUF': 'South America',
    
    # North America
    'USA': 'North America',
    'CAN': 'North America',
    'MEX': 'North America',
    'PAN': 'North America',
    'JAM': 'North America',
    'HAI': 'North America',
    'HON': 'North America',
    'TRI': 'North America',
    'CRC': 'North America',
    'BER': 'North America',
    'DOM': 'North America',
    'SKN': 'North America',
    'GRN': 'North America',
    'ATG': 'North America',
    'BRB': 'North America',
    'CUB': 'North America',
    'SLV': 'North America',
    'GUA': 'North America',
    'MTQ': 'North America',
    'GLP': 'North America',
    'MSR': 'North America',
    'CUW': 'North America',
    
    # Asia
    'AZE': 'Asia',
    'CYP': 'Asia',
    'ISR': 'Asia',
    'IRN': 'Asia',
    'KOR': 'Asia',
    'CHN': 'Asia',
    'JPN': 'Asia',
    'QAT': 'Asia',
    'PHI': 'Asia',
    'PAK': 'Asia',
    'LAO': 'Asia',
    'CAM': 'Asia',
    'TJK': 'Asia',
    'OMA': 'Asia',
    'KAZ': 'Asia',
    'IDN': 'Asia',
    'PRK': 'Asia',
    'IRQ': 'Asia',
    'THA': 'Asia',
    'BAN': 'Asia',
    'UZB': 'Asia',
    'PLE': 'Asia',
    
    # Oceania
    'AUS': 'Oceania',
    'NZL': 'Oceania',
    'TAH': 'Oceania',
    'NCL': 'Oceania',
    
    # Missing / unknown
    'NAN': None
}

df_player_updated = df_player.copy()
df_player_updated['continent'] = (df_player_updated['nationality'].map(nationality_to_continent))
df_player_updated.head()

,player,nationality,position,team,league,age,matches,minutes,goals,assists,season,assists_missing,ga_per_90,continent
0,Agustín Abadía,ESP,MF,Compostela,La Liga,33.0,14,378,0,0,1995-1996,True,0.0,Europe
1,Beniamino Abate,ITA,GK,Cagliari,Serie A,33.0,15,1350,0,0,1995-1996,True,0.0,Europe
2,Giovanni Abate,ITA,MF,Sampdoria,Serie A,19.0,1,56,0,0,1995-1996,True,0.0,Europe
3,Denis Abed,FRA,FW,Lille,Division 1,26.0,14,925,0,0,1995-1996,True,0.0,Europe
4,Gary Ablett,ENG,DF,Everton,Premier League,29.0,13,1017,0,0,1995-1996,False,0.0,Europe

In [16]:
unmapped = df_player_updated.loc[
    df_player_updated['continent'].isna(),
    'nationality'
].unique()

print(unmapped)

['NAN']

In [15]:
nationality_to_continent.update({

    'GER': 'Europe',
    'EST': 'Europe',

    'MAS': 'Asia',

    'SMN': 'North America',
    'MTN': 'North America',

    'MRI': 'Africa',
    'CTA': 'Africa',

    'NAN': None
})

df_player_updated['continent'] = (df_player_updated['nationality'].map(nationality_to_continent))
df_player_updated.head()

,player,nationality,position,team,league,age,matches,minutes,goals,assists,season,assists_missing,ga_per_90,continent
0,Agustín Abadía,ESP,MF,Compostela,La Liga,33.0,14,378,0,0,1995-1996,True,0.0,Europe
1,Beniamino Abate,ITA,GK,Cagliari,Serie A,33.0,15,1350,0,0,1995-1996,True,0.0,Europe
2,Giovanni Abate,ITA,MF,Sampdoria,Serie A,19.0,1,56,0,0,1995-1996,True,0.0,Europe
3,Denis Abed,FRA,FW,Lille,Division 1,26.0,14,925,0,0,1995-1996,True,0.0,Europe
4,Gary Ablett,ENG,DF,Everton,Premier League,29.0,13,1017,0,0,1995-1996,False,0.0,Europe

In [17]:
df_player_updated[df_player_updated['nationality'] == 'NAN']

,player,nationality,position,team,league,age,matches,minutes,goals,assists,season,assists_missing,ga_per_90,continent
36,Alejandro,NAN,NaN,Albacete,La Liga,24.0,31,2693,1,0,1995-1996,True,0.0334,None
252,Gorka Bidaurrazaga,NAN,NaN,Athletic Club,La Liga,22.0,4,191,0,0,1995-1996,True,0.0000,None
434,Antonio Castro Fernández,NAN,NaN,Compostela,La Liga,23.0,8,484,1,0,1995-1996,True,0.1860,None
460,Lee Charles,NAN,FW,QPR,Premier League,23.0,4,107,0,0,1995-1996,False,0.0000,None
465,Chechu,NAN,NaN,Oviedo,La Liga,17.0,1,25,1,0,1995-1996,True,3.6000,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61900,Hakim El Mokeddem,NAN,NaN,Toulouse,Ligue 1,19.0,2,25,0,0,2018-2019,False,0.0000,None
62803,Anthony Walongwa,NAN,DF,Nantes,Ligue 1,24.0,1,90,0,0,2018-2019,False,0.0000,None
64677,Jeremy Ngakia,NAN,DF,West Ham United,Premier League,18.0,5,440,0,0,2019-2020,False,0.0000,None
68173,Sidnei Tavares,NAN,MF,Leicester City,Premier League,18.0,2,85,0,0,2020-2021,False,0.0000,None
70372,Jeremy Ngakia,NAN,DF,Watford,Premier League,20.0,16,903,0,0,2021-2022,False,0.0000,None

In [18]:
nan_nationality_players = df_player_updated.loc[
    df_player['nationality'] == 'NAN',
    'player'
].nunique()

print("Unique players with NAN nationality:", nan_nationality_players)

Unique players with NAN nationality: 153

In [22]:
nan_players = df_player_updated.loc[
    df_player_updated['nationality'] == 'NAN',
    'player'
].unique()

player_nationality_check = df_player_updated[
    df_player_updated['player'].isin(nan_players)
][['player', 'nationality', 'season']].sort_values('player')

player_nationality_check['nationality'].unique()

array(['NAN', 'ESP', 'ITA'], dtype=object)

In [23]:
known_nationalities = (
    df_player[df_player['nationality'] != 'NAN']
    .groupby('player')['nationality']
    .agg(lambda x: x.mode().iloc[0])
)

df_player_updated['nationality'] = df_player_updated.apply(
    lambda row: (
        known_nationalities.get(row['player'])
        if row['nationality'] == 'NAN'
        else row['nationality']
    ),
    axis=1
)

print(
    "Remaining NAN nationalities:",
    (df_player['nationality'] == 'NAN').sum()
)

Remaining NAN nationalities: 191

In [26]:
df_player_updated['nationality'].unique()

array(['ESP', 'ITA', 'FRA', 'ENG', 'NGA', 'BEN', 'NOR', 'TUR', 'BEL',
       'GER', 'BRA', None, 'AUS', 'DEN', 'SWE', 'CRO', 'PAR', 'SRB',
       'ARG', 'MAD', 'COL', 'ARM', 'HAI', 'IRL', 'GUI', 'POL', 'CIV',
       'BUL', 'MNE', 'ALG', 'CZE', 'NED', 'ISL', 'RUS', 'CMR', 'NIR',
       'WAL', 'TUN', 'GDR', 'SCO', 'USA', 'AUT', 'MAR', 'SUI', 'GRE',
       'SLE', 'MTQ', 'URU', 'POR', 'MLI', 'ROU', 'GUF', 'LBR', 'PER',
       'PAN', 'UKR', 'SVK', 'GLP', 'JAM', 'COD', 'SEN', 'SVN', 'RSA',
       'MSR', 'AZE', 'BIH', 'BRB', 'ZIM', 'HON', 'TRI', 'LTU', 'GEO',
       'CIS', 'GHA', 'VEN', 'EQG', 'BOL', 'MKD', 'HUN', 'YUG', 'CHA',
       'FIN', 'CHI', 'EGY', 'CYP', 'ISR', 'ALB', 'URS', 'LUX', 'TOG',
       'CGO', 'BLR', 'REU', 'GUY', 'CAN', 'ANG', 'CRC', 'CPV', 'EST',
       'IRN', 'SKN', 'MCO', 'GIB', 'KOR', 'NIG', 'BER', 'MWI', 'MDA',
       'GNB', 'CHN', 'MAS', 'SCG', 'ECU', 'JPN', 'LVA', 'TAH', 'MEX',
       'ZAM', 'NAM', 'SMN', 'DOM', 'MTN', 'NZL', 'BFA', 'LIB', 'SEY',
       'COM', 'LIE', 'MLT', 'GAB', 'SMR', 'GRN', 'NCL', 'QAT', 'MRI',
       'PHI', 'LBY', 'PAK', 'ATG', 'ERI', 'MOZ', 'CTA', 'LAO', 'KEN',
       'CAM', 'KVX', 'TJK', 'OMA', 'KAZ', 'BDI', 'SOM', 'SUR', 'CUW',
       'IDN', 'FRO', 'GAM', 'PRK', 'IRQ', 'UGA', 'THA', 'SLV', 'BAN',
       'GUA', 'CUB', 'TAN', 'UZB', 'PLE'], dtype=object)

In [27]:
df_player_updated['nationality'].value_counts(dropna=False).head(20)

nationality
ESP    10401
FRA     9628
ITA     8992
GER     6745
ENG     5922
BRA     2915
ARG     2410
NED     1155
POR     1093
SEN      962
SRB      922
URU      841
CRO      832
IRL      797
CIV      770
DEN      706
BEL      705
CMR      691
SUI      683
SCO      648
Name: count, dtype: int64

In [28]:
df_player_updated['nationality'].isna().sum()

186

In [31]:
df_player_updated.loc[
    df_player_updated['nationality'].isna(),
    'player'
].nunique()

148

In [32]:
missing_players = (
    df_player_updated.loc[
        df_player_updated['nationality'].isna(),
        'player'
    ]
    .unique()
)

df_player_updated.loc[
    df_player_updated['player'].isin(missing_players),
    ['player', 'nationality', 'position', 'season', 'team', 'league']
].sort_values('player')

,player,nationality,position,season,team,league
15002,Abdoulaye Barry,None,NaN,2001-2002,Bordeaux,Division 1
8122,Adam Farley,None,DF,1998-1999,Everton,Premier League
19009,Ahmed Mohamed Saïd,None,NaN,2002-2003,Le Havre,Ligue 1
34326,Alban Joinel,None,GK,2008-2009,Lorient,Ligue 1
12337,Alberto Alejandro,None,FW,2000-2001,Real Sociedad,La Liga
...,...,...,...,...,...,...
17724,Yuri Breviario,None,NaN,2002-2003,Atalanta,Serie A
15163,Yuri Breviario,None,NaN,2001-2002,Atalanta,Serie A
7164,Zoran Tomčić,None,FW,1997-1998,Wolfsburg,Bundesliga
4189,Álvaro Pérez,None,NaN,1996-1997,Athletic Club,La Liga
17468,Óscar Aparicio,None,GK,2002-2003,Rayo Vallecano,La Liga

In [33]:
missing_forward_players = df_player_updated.loc[
    (df_player_updated['nationality'].isna()) &
    (df_player_updated['position'].isin(['FW', 'FW/MF']))
]

print("Missing nationality rows for forwards:", len(missing_forward_players))

print(
    "Unique forwards with missing nationality:",
    missing_forward_players['player'].nunique()
)

Missing nationality rows for forwards: 13
Unique forwards with missing nationality: 11

In [34]:
missing_forward_players = (
    df_player_updated.loc[
        (df_player_updated['nationality'].isna()) &
        (df_player_updated['position'].isin(['FW', 'FW/MF'])),
        ['player', 'position', 'season', 'team', 'league']
    ]
    .sort_values('player')
)

missing_forward_players

,player,position,season,team,league
12337,Alberto Alejandro,FW,2000-2001,Real Sociedad,La Liga
14861,Alberto Alejandro,FW,2001-2002,Real Sociedad,La Liga
42448,Brice Jovial,FW,2011-2012,Dijon,Ligue 1
18226,Cédrick Fiston,FW,2002-2003,Bordeaux,Ligue 1
3092,Demir Duric,FW,1996-1997,St Pauli,Bundesliga
58306,Dennis Eckert,FW,2017-2018,Celta Vigo,La Liga
60962,Dennis Eckert,FW,2018-2019,Celta Vigo,La Liga
26931,Djim Ngom,FW,2005-2006,Marseille,Ligue 1
460,Lee Charles,FW,1995-1996,QPR,Premier League
12244,Nick Wright,FW,1999-2000,Watford,Premier League
1092,Richard Irving,FW,1995-1996,Nottingham Forest,Premier League
29398,Soilhyo Mété,FW,2006-2007,Nantes,Ligue 1
7164,Zoran Tomčić,FW,1997-1998,Wolfsburg,Bundesliga

In [35]:
manual_nationality_fix = {
    'Alberto Alejandro': 'ESP',
    'Brice Jovial': 'FRA',
    'Cédrick Fiston': 'GLP',
    'Demir Duric': 'SRB',
    'Dennis Eckert': 'GER',
    'Djim Ngom': 'SEN',
    'Lee Charles': 'ENG',
    'Nick Wright': 'ENG',
    'Richard Irving': 'ENG',
    'Soilhyo Mété': 'FRA',
    'Zoran Tomčić': 'CRO'
}

mask = df_player_updated['nationality'].isna()

df_player_updated.loc[mask, 'nationality'] = (
    df_player_updated.loc[mask, 'player']
    .map(manual_nationality_fix)
)

In [36]:
remaining_missing_forwards = df_player_updated.loc[
    (df_player_updated['nationality'].isna()) &
    (df_player_updated['position'].isin(['FW', 'FW/MF'])),
    ['player', 'position', 'season', 'team', 'league']
]

remaining_missing_forwards

Empty DataFrame
Columns: [player, position, season, team, league]
Index: []

In [37]:
print(
    "Remaining missing forward nationalities:",
    remaining_missing_forwards['player'].nunique()
)

Remaining missing forward nationalities: 0

In [38]:
df_player_updated.head()

,player,nationality,position,team,league,age,matches,minutes,goals,assists,season,assists_missing,ga_per_90,continent
0,Agustín Abadía,ESP,MF,Compostela,La Liga,33.0,14,378,0,0,1995-1996,True,0.0,Europe
1,Beniamino Abate,ITA,GK,Cagliari,Serie A,33.0,15,1350,0,0,1995-1996,True,0.0,Europe
2,Giovanni Abate,ITA,MF,Sampdoria,Serie A,19.0,1,56,0,0,1995-1996,True,0.0,Europe
3,Denis Abed,FRA,FW,Lille,Division 1,26.0,14,925,0,0,1995-1996,True,0.0,Europe
4,Gary Ablett,ENG,DF,Everton,Premier League,29.0,13,1017,0,0,1995-1996,False,0.0,Europe

In [39]:
df_player_updated['continent'] = (
    df_player_updated['nationality']
    .map(nationality_to_continent)
)

df_player_updated.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74262 entries, 0 to 74261
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   player           74262 non-null  object
 1   nationality      74089 non-null  object
 2   position         74048 non-null  object
 3   team             74262 non-null  object
 4   league           74262 non-null  object
 5   age              74251 non-null  float64
 6   matches          74262 non-null  int64
 7   minutes          74262 non-null  int64
 8   goals            74262 non-null  int64
 9   assists          74262 non-null  int64
 10  season           74262 non-null  object
 11  assists_missing  74262 non-null  bool
 12  ga_per_90        74262 non-null  float64
 13  continent        74089 non-null  object
dtypes: bool(1), float64(2), int64(4), object(7)
memory usage: 7.4+ MB

In [40]:
continent_players = df_player_updated.groupby(
    ['season', 'continent'], as_index=False)['player'].nunique().rename(columns={
        'player':'player_count'})
continent_players.head()

      season      continent  player_count
0  1995-1996         Africa            77
1  1995-1996           Asia             3
2  1995-1996         Europe          2146
3  1995-1996  North America            25
4  1995-1996        Oceania             8

In [44]:
eligible_pop_cont = eligible_pop[(eligible_pop['Year'] >= 1995) & (eligible_pop['Year'] <= 2022)].copy()
eligible_pop_cont.head()

    Year      Continent   Population
18  1995         Africa  117798368.0
19  1995           Asia  605853977.5
20  1995         Europe  120585732.5
21  1995  North America   73352823.5
22  1995        Oceania    4677394.5

In [45]:
continent_players['season_start'] = (
    continent_players['season']
    .str[:4]
    .astype(int)
)

continent_players.head()

      season      continent  player_count  season_start
0  1995-1996         Africa            77          1995
1  1995-1996           Asia             3          1995
2  1995-1996         Europe          2146          1995
3  1995-1996  North America            25          1995
4  1995-1996        Oceania             8          1995

In [46]:
# Prepare population dataset
population_merge = eligible_pop_cont.rename(columns={
    'Year': 'year',
    'Continent': 'continent',
    'Population': 'total_pop'
})

# Merge population with player counts
continent_analysis = population_merge.merge(
    continent_players,
    left_on=['year', 'continent'],
    right_on=['season_start', 'continent'],
    how='left'
)

continent_analysis.head()

   year      continent    total_pop     season  player_count  season_start
0  1995         Africa  117798368.0  1995-1996            77          1995
1  1995           Asia  605853977.5  1995-1996             3          1995
2  1995         Europe  120585732.5  1995-1996          2146          1995
3  1995  North America   73352823.5  1995-1996            25          1995
4  1995        Oceania    4677394.5  1995-1996             8          1995

In [47]:
continent_analysis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   year          168 non-null    int64
 1   continent     168 non-null    object
 2   total_pop     168 non-null    float64
 3   season        168 non-null    object
 4   player_count  168 non-null    int64
 5   season_start  168 non-null    int64
dtypes: float64(1), int64(3), object(2)
memory usage: 8.0+ KB