In [2]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 

pd.set_option('display.max_columns', None)

In [25]:
population_path = '/Users/muhammadhamza/striker_era_ranking/data/raw/external/population-data-updated.csv'
balondor_path = '/Users/muhammadhamza/striker_era_ranking/data/raw/ballon_dor/ballon_dor_winners.csv'
player_path = '/Users/muhammadhamza/striker_era_ranking/data/raw/fbref/all_seasons_combined.csv'
df_pop = pd.read_csv(population_path)
df_bdr = pd.read_csv(balondor_path)
df_player = pd.read_csv(player_path)

In [5]:
df_pop.head()

,IndicatorId,IndicatorName,IndicatorShortName,Source,SourceYear,Author,LocationId,Location,Iso2,Iso3,TimeId,Time,VariantId,Variant,SexId,Sex,AgeId,AgeStart,AgeEnd,Age,CategoryId,Category,EstimateTypeId,EstimateType,EstimateMethodId,EstimateMethod,Value
0,47,Population by 1-year age groups and sex,Annual population by 1-year age groups and by sex,World Population Prospects,2024,United Nations Population Division,8,Albania,AL,ALB,43,1992,4,Median,1,Male,113,16,16,16,0,Not applicable,1,Model-based Estimates,2,Interpolation,30596.0
1,47,Population by 1-year age groups and sex,Annual population by 1-year age groups and by sex,World Population Prospects,2024,United Nations Population Division,8,Albania,AL,ALB,43,1992,4,Median,1,Male,114,17,17,17,0,Not applicable,1,Model-based Estimates,2,Interpolation,30175.0
2,47,Population by 1-year age groups and sex,Annual population by 1-year age groups and by sex,World Population Prospects,2024,United Nations Population Division,8,Albania,AL,ALB,43,1992,4,Median,1,Male,115,18,18,18,0,Not applicable,1,Model-based Estimates,2,Interpolation,29649.0
3,47,Population by 1-year age groups and sex,Annual population by 1-year age groups and by sex,World Population Prospects,2024,United Nations Population Division,8,Albania,AL,ALB,43,1992,4,Median,1,Male,116,19,19,19,0,Not applicable,1,Model-based Estimates,2,Interpolation,30238.0
4,47,Population by 1-year age groups and sex,Annual population by 1-year age groups and by sex,World Population Prospects,2024,United Nations Population Division,8,Albania,AL,ALB,43,1992,4,Median,1,Male,92,20,20,20,0,Not applicable,1,Model-based Estimates,2,Interpolation,30698.0

In [11]:
df_pop['Variant'].unique()

array(['Median'], dtype=object)

In [14]:
population_raw = df_pop[['Time', 'Location', 'Age', 'Value']].copy()

population_raw = population_raw.rename(columns={
    'Time': 'Year', 
    'Location': 'Country',
    'Value': 'Population'
})

population_raw.head()

   Year  Country  Age  Population
0  1992  Albania   16     30596.0
1  1992  Albania   17     30175.0
2  1992  Albania   18     29649.0
3  1992  Albania   19     30238.0
4  1992  Albania   20     30698.0

In [15]:
duplicate_check = population_raw.duplicated(subset=[
    'Year', 'Country', 'Age'
]).sum()

duplicate_check

0

In [16]:
population_raw['Country'].unique()

array(['Albania', 'Algeria', 'Andorra', 'Angola', 'Argentina', 'Austria',
       'Armenia', 'Belgium', 'Bolivia (Plurinational State of)',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Belize',
       'Bulgaria', 'Burundi', 'Belarus', 'Cameroon', 'Cabo Verde',
       'Central African Republic', 'Chad', 'Chile', 'Colombia', 'Comoros',
       'Mayotte', 'Congo', 'Democratic Republic of the Congo',
       'Costa Rica', 'Croatia', 'Czechia', 'Benin', 'Denmark', 'Ecuador',
       'El Salvador', 'Equatorial Guinea', 'Ethiopia', 'Eritrea',
       'Estonia', 'Faroe Islands', 'Falkland Islands (Malvinas)',
       'Finland', 'France', 'French Guiana', 'Djibouti', 'Gabon',
       'Georgia', 'Gambia', 'Germany', 'Ghana', 'Gibraltar', 'Greece',
       'Guatemala', 'Guinea', 'Guyana', 'Honduras', 'Hungary', 'Iceland',
       'Ireland', 'Italy', "Côte d'Ivoire", 'Kenya',
       'Kosovo (under UNSC res. 1244)', 'Lesotho', 'Latvia', 'Liberia',
       'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar',
       'Malawi', 'Mali', 'Malta', 'Mauritania', 'Mauritius', 'Mexico',
       'Monaco', 'Republic of Moldova', 'Montenegro', 'Morocco',
       'Mozambique', 'Namibia', 'Netherlands', 'Nicaragua', 'Niger',
       'Nigeria', 'Norway', 'Panama', 'Paraguay', 'Peru', 'Poland',
       'Portugal', 'Guinea-Bissau', 'Réunion', 'Romania',
       'Russian Federation', 'Rwanda', 'Saint Helena', 'San Marino',
       'Sao Tome and Principe', 'Senegal', 'Serbia', 'Seychelles',
       'Sierra Leone', 'Slovakia', 'Slovenia', 'Somalia', 'South Africa',
       'Zimbabwe', 'Spain', 'South Sudan', 'Sudan', 'Western Sahara',
       'Suriname', 'Eswatini', 'Sweden', 'Switzerland', 'Togo', 'Tunisia',
       'Türkiye', 'Uganda', 'Ukraine', 'North Macedonia', 'Egypt',
       'United Kingdom', 'Guernsey', 'Jersey', 'Isle of Man',
       'United Republic of Tanzania', 'Burkina Faso', 'Uruguay',
       'Venezuela (Bolivarian Republic of)', 'Zambia'], dtype=object)

In [18]:
country_to_continent = {
    # Africa
    'Algeria': 'Africa',
    'Angola': 'Africa',
    'Benin': 'Africa',
    'Botswana': 'Africa',
    'Burkina Faso': 'Africa',
    'Burundi': 'Africa',
    'Cabo Verde': 'Africa',
    'Cameroon': 'Africa',
    'Central African Republic': 'Africa',
    'Chad': 'Africa',
    'Comoros': 'Africa',
    'Congo': 'Africa',
    'Democratic Republic of the Congo': 'Africa',
    "Côte d'Ivoire": 'Africa',
    'Djibouti': 'Africa',
    'Egypt': 'Africa',
    'Equatorial Guinea': 'Africa',
    'Eritrea': 'Africa',
    'Eswatini': 'Africa',
    'Ethiopia': 'Africa',
    'Gabon': 'Africa',
    'Gambia': 'Africa',
    'Ghana': 'Africa',
    'Guinea': 'Africa',
    'Guinea-Bissau': 'Africa',
    'Kenya': 'Africa',
    'Lesotho': 'Africa',
    'Liberia': 'Africa',
    'Libya': 'Africa',
    'Madagascar': 'Africa',
    'Malawi': 'Africa',
    'Mali': 'Africa',
    'Mauritania': 'Africa',
    'Mauritius': 'Africa',
    'Mayotte': 'Africa',
    'Morocco': 'Africa',
    'Mozambique': 'Africa',
    'Namibia': 'Africa',
    'Niger': 'Africa',
    'Nigeria': 'Africa',
    'Réunion': 'Africa',
    'Rwanda': 'Africa',
    'Saint Helena': 'Africa',
    'Sao Tome and Principe': 'Africa',
    'Senegal': 'Africa',
    'Seychelles': 'Africa',
    'Sierra Leone': 'Africa',
    'Somalia': 'Africa',
    'South Africa': 'Africa',
    'South Sudan': 'Africa',
    'Sudan': 'Africa',
    'Togo': 'Africa',
    'Tunisia': 'Africa',
    'Uganda': 'Africa',
    'United Republic of Tanzania': 'Africa',
    'Western Sahara': 'Africa',
    'Zambia': 'Africa',
    'Zimbabwe': 'Africa',

    # Europe
    'Albania': 'Europe',
    'Andorra': 'Europe',
    'Armenia': 'Europe',
    'Austria': 'Europe',
    'Belarus': 'Europe',
    'Belgium': 'Europe',
    'Bosnia and Herzegovina': 'Europe',
    'Bulgaria': 'Europe',
    'Croatia': 'Europe',
    'Czechia': 'Europe',
    'Denmark': 'Europe',
    'Estonia': 'Europe',
    'Faroe Islands': 'Europe',
    'Finland': 'Europe',
    'France': 'Europe',
    'Georgia': 'Europe',
    'Germany': 'Europe',
    'Gibraltar': 'Europe',
    'Greece': 'Europe',
    'Guernsey': 'Europe',
    'Hungary': 'Europe',
    'Iceland': 'Europe',
    'Ireland': 'Europe',
    'Isle of Man': 'Europe',
    'Italy': 'Europe',
    'Jersey': 'Europe',
    'Kosovo (under UNSC res. 1244)': 'Europe',
    'Latvia': 'Europe',
    'Liechtenstein': 'Europe',
    'Lithuania': 'Europe',
    'Luxembourg': 'Europe',
    'Malta': 'Europe',
    'Monaco': 'Europe',
    'Montenegro': 'Europe',
    'Netherlands': 'Europe',
    'North Macedonia': 'Europe',
    'Norway': 'Europe',
    'Poland': 'Europe',
    'Portugal': 'Europe',
    'Republic of Moldova': 'Europe',
    'Romania': 'Europe',
    'Russian Federation': 'Europe',
    'San Marino': 'Europe',
    'Serbia': 'Europe',
    'Slovakia': 'Europe',
    'Slovenia': 'Europe',
    'Spain': 'Europe',
    'Sweden': 'Europe',
    'Switzerland': 'Europe',
    'Türkiye': 'Europe',
    'Ukraine': 'Europe',
    'United Kingdom': 'Europe',

    # North America
    'Belize': 'North America',
    'Costa Rica': 'North America',
    'El Salvador': 'North America',
    'Guatemala': 'North America',
    'Honduras': 'North America',
    'Mexico': 'North America',
    'Nicaragua': 'North America',
    'Panama': 'North America',

    # South America
    'Argentina': 'South America',
    'Bolivia (Plurinational State of)': 'South America',
    'Brazil': 'South America',
    'Chile': 'South America',
    'Colombia': 'South America',
    'Ecuador': 'South America',
    'Falkland Islands (Malvinas)': 'South America',
    'French Guiana': 'South America',
    'Guyana': 'South America',
    'Paraguay': 'South America',
    'Peru': 'South America',
    'Suriname': 'South America',
    'Uruguay': 'South America',
    'Venezuela (Bolivarian Republic of)': 'South America',
}

population_raw['Continent'] = population_raw['Country'].map(country_to_continent)

population_raw.head()

   Year  Country  Age  Population Continent
0  1992  Albania   16     30596.0    Europe
1  1992  Albania   17     30175.0    Europe
2  1992  Albania   18     29649.0    Europe
3  1992  Albania   19     30238.0    Europe
4  1992  Albania   20     30698.0    Europe

In [21]:
population_continent = (
    population_raw.groupby(['Year', 'Continent', 'Age'], as_index=False)['Population'].sum()
)

population_continent.head()

   Year Continent  Age  Population
0  1992    Africa   16   7437675.5
1  1992    Africa   17   7183377.0
2  1992    Africa   18   6929948.0
3  1992    Africa   19   6699214.0
4  1992    Africa   20   6477465.5

In [22]:
duplicate_check_cont = population_continent.duplicated(subset=[
    'Year', 'Continent', 'Age'
]).sum()

duplicate_check_cont

0

In [24]:
eligible_pop = (
    population_continent.groupby(['Year'], as_index=False)['Population'].sum()
)

eligible_pop.head()

   Year   Population
0  1992  303038218.0
1  1993  307129659.0
2  1994  311220331.0
3  1995  315181236.5
4  1996  319056855.5

In [26]:
df_player.head()

,player,nationality,position,team,league,age,matches,minutes,goals,assists,season,assists_missing,ga_per_90
0,Agustín Abadía,ESP,MF,Compostela,La Liga,33.0,14,378,0,0,1995-1996,True,0.0
1,Beniamino Abate,ITA,GK,Cagliari,Serie A,33.0,15,1350,0,0,1995-1996,True,0.0
2,Giovanni Abate,ITA,MF,Sampdoria,Serie A,19.0,1,56,0,0,1995-1996,True,0.0
3,Denis Abed,FRA,FW,Lille,Division 1,26.0,14,925,0,0,1995-1996,True,0.0
4,Gary Ablett,ENG,DF,Everton,Premier League,29.0,13,1017,0,0,1995-1996,False,0.0

In [28]:
df_player['nationality'].unique()

array(['ESP', 'ITA', 'FRA', 'ENG', 'NGA', 'BEN', 'NOR', 'TUR', 'BEL',
       'GER', 'BRA', 'NAN', 'AUS', 'DEN', 'SWE', 'CRO', 'PAR', 'SRB',
       'ARG', 'MAD', 'COL', 'ARM', 'HAI', 'IRL', 'GUI', 'POL', 'CIV',
       'BUL', 'MNE', 'ALG', 'CZE', 'NED', 'ISL', 'RUS', 'CMR', 'NIR',
       'WAL', 'TUN', 'GDR', 'SCO', 'USA', 'AUT', 'MAR', 'SUI', 'GRE',
       'SLE', 'MTQ', 'URU', 'POR', 'MLI', 'ROU', 'GUF', 'LBR', 'PER',
       'PAN', 'UKR', 'SVK', 'GLP', 'JAM', 'COD', 'SEN', 'SVN', 'RSA',
       'MSR', 'AZE', 'BIH', 'BRB', 'ZIM', 'HON', 'TRI', 'LTU', 'GEO',
       'CIS', 'GHA', 'VEN', 'EQG', 'BOL', 'MKD', 'HUN', 'YUG', 'CHA',
       'FIN', 'CHI', 'EGY', 'CYP', 'ISR', 'ALB', 'URS', 'LUX', 'TOG',
       'CGO', 'BLR', 'REU', 'GUY', 'CAN', 'ANG', 'CRC', 'CPV', 'EST',
       'IRN', 'SKN', 'MCO', 'GIB', 'KOR', 'NIG', 'BER', 'MWI', 'MDA',
       'GNB', 'CHN', 'MAS', 'SCG', 'ECU', 'JPN', 'LVA', 'TAH', 'MEX',
       'ZAM', 'NAM', 'SMN', 'DOM', 'MTN', 'NZL', 'BFA', 'LIB', 'SEY',
       'COM', 'LIE', 'MLT', 'GAB', 'SMR', 'GRN', 'NCL', 'QAT', 'MRI',
       'PHI', 'LBY', 'PAK', 'ATG', 'ERI', 'MOZ', 'CTA', 'LAO', 'KEN',
       'CAM', 'KVX', 'TJK', 'OMA', 'KAZ', 'BDI', 'SOM', 'SUR', 'CUW',
       'IDN', 'FRO', 'GAM', 'PRK', 'IRQ', 'UGA', 'THA', 'SLV', 'BAN',
       'GUA', 'CUB', 'TAN', 'UZB', 'PLE'], dtype=object)